name: Generate Lots of Logs

on:
  workflow_dispatch:
  push:
jobs:
  generate_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Logs
        run: |
          for i in {1..1000}; do
            echo "Log entry $i"
          done
        shell: bash
